version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: aurora.app:1.0
    container_name: aurora.app
    restart: always
    env_file: .env
    command: npm run dev
    volumes:
      - .:/home/node/aurora.app/
      # Compose directory 
      - /opt/compose:/opt/compose
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "7777:3000"
