version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: node:20-alpine
    container_name: aurora.app
    restart: unless-stopped
    env_file: .env
    command: npm run dev
    volumes:
      - .:/home/node/aurora.app/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "7777:3000"